name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Ruby (2.7)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        
    - name: Install NodeJS (16)
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Code Climate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    
    - name: Install bundler
      run: |
        gem install bundler

    - name: Install dependencies
      run: |
        bundle install
    
    - name: Install node_modules
      run: |
        npm install
    
    - name: Set up database
      run: |
        bundle exec rake db:create db:migrate
    
    - name: run RSpec tests and capture coverage
      run: |
        bundle exec rspec
        ./cc-test-reporter format-coverage --output coverage/codeclimate.$SUITE.json --input-type simplecov
    
    - name: run Cucumber tests and capture coverage
      run: |
        bundle exec cucumber --retry 2
        ./cc-test-reporter format-coverage --output coverage/codeclimate.$SUITE.json --input-type simplecov
        
    - name: run ESLinting
      run: |
        npm run lint
        
    - name: Publish code coverage
      run: |
        export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
        ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
        ./cc-test-reporter upload-coverage --id ${{ secrets.CODE_CLIMATE_ID }}
        ./cc-test-reporter after-build --id ${{ secrets.CODE_CLIMATE_ID }}
